package ComTests;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import javaOpintoloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.10 14:31:10 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class KurssitTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa55 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa55() throws SailoException {    // Kurssit: 55
    Kurssit kurssit2 = new Kurssit(); 
    assertEquals("From: Kurssit line: 58", 0, kurssit2.getLkm()); 
    Kurssi k3 = new Kurssi(); 
    k3.annaVakio(); 
    kurssit2.lisaa(k3); 
    assertEquals("From: Kurssit line: 62", 1, kurssit2.getLkm()); 
  } // Generated by ComTest END
}