package ComTests;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import javaOpintoloki.*;
// Generated by ComTest END
import static javaOpintoloki.Kurssi.*;

/**
 * Test class made by ComTest
 * @version 2019.05.03 22:17:57 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class KurssiTest {



  // Generated by ComTest BEGIN
  /** testToString274 */
  @Test
  public void testToString274() {    // Kurssi: 274
    Kurssi kurssi = new Kurssi(); 
    kurssi.parse("   1   ,   2   ,  3   ,  4   ,   5"); 
    assertEquals("From: Kurssi line: 277", true, kurssi.toString().startsWith("1,2,3,4,5")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testMain310 */
  @Test
  public void testMain310() {    // Kurssi: 310
    Kurssi k1 = new Kurssi(); 
    k1.annaVakio(); 
    assertEquals("From: Kurssi line: 313", "TIEP111", k1.getTunnus()); 
  } // Generated by ComTest END
}