package ComTests;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import javaOpintoloki.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.05.03 21:59:04 // Generated by ComTest
 *
 */
@SuppressWarnings("unused")
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testAnna91 */
  @Test
  public void testAnna91() {    // Suoritus: 91
    Suoritus har = new Suoritus(); 
    har.parse("1,2,3"); 
    assertEquals("From: Suoritus line: 94", "1", har.anna(0)); 
    assertEquals("From: Suoritus line: 95", "2", har.anna(1)); 
    assertEquals("From: Suoritus line: 96", "3", har.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone143 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone143() throws CloneNotSupportedException {    // Suoritus: 143
    Suoritus har = new Suoritus(); 
    har.parse("1,2,3"); 
    Suoritus kopio = har.clone(); 
    assertEquals("From: Suoritus line: 148", har.toString(), kopio.toString()); 
    har.parse("1,3,2"); 
    assertEquals("From: Suoritus line: 150", false, kopio.toString().equals(har.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString204 */
  @Test
  public void testToString204() {    // Suoritus: 204
    Suoritus harrastus = new Suoritus(); 
    harrastus.parse("   1   ,  2  ,   3"); 
    assertEquals("From: Suoritus line: 207", "1,2,3", harrastus.toString()); 
  } // Generated by ComTest END
}